# Use the official Node.js 14 image as a parent image
FROM node:14-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Build the React app for production
RUN npm run build

# Use the official Nginx image as a parent image
FROM nginx:alpine

# Copy the build output from the build stage to the nginx web root
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]